version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_rom-v1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rom_db
      MYSQL_USER: rom_user
      MYSQL_PASSWORD: rom_password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: